In [109]:
import torch

In [110]:
z=torch.zeros(2,dtype=torch.int32)

In [111]:
z

tensor([0, 0], dtype=torch.int32)

In [112]:
o=torch.ones(2,3,dtype= torch.float16)

In [113]:
o

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float16)

In [114]:
r=torch.randn(2,2)

In [115]:
r

tensor([[-0.4445, -1.0648],
        [ 0.8202, -0.0099]])

In [116]:
r.shape

torch.Size([2, 2])

In [117]:
r.size()

torch.Size([2, 2])

In [118]:
r=r.reshape([4,1])

In [119]:
r

tensor([[-0.4445],
        [-1.0648],
        [ 0.8202],
        [-0.0099]])

In [120]:
torch.add(r,r)

tensor([[-0.8890],
        [-2.1296],
        [ 1.6403],
        [-0.0199]])

In [121]:
r.add(r)

tensor([[-0.8890],
        [-2.1296],
        [ 1.6403],
        [-0.0199]])

In [122]:
r

tensor([[-0.4445],
        [-1.0648],
        [ 0.8202],
        [-0.0099]])

In [123]:
r.add_(r)

tensor([[-0.8890],
        [-2.1296],
        [ 1.6403],
        [-0.0199]])

In [124]:
r

tensor([[-0.8890],
        [-2.1296],
        [ 1.6403],
        [-0.0199]])

In [125]:
r.div(r)

tensor([[1.],
        [1.],
        [1.],
        [1.]])

In [126]:
torch.div(r,r)

tensor([[1.],
        [1.],
        [1.],
        [1.]])

In [127]:
rnd=torch.rand(5,5)

In [128]:
rnd[1,1]

tensor(0.9038)

In [129]:
rnd[1,:2]

tensor([0.9163, 0.9038])

In [130]:
rnd[1,:4]

tensor([0.9163, 0.9038, 0.7019, 0.3004])

In [131]:
rnd[:2,:2]

tensor([[0.3561, 0.6286],
        [0.9163, 0.9038]])

In [132]:
type(rnd[1,1].item())

float

In [133]:
rnd.shape

torch.Size([5, 5])

In [134]:
rnd.reshape([25,1])

tensor([[0.3561],
        [0.6286],
        [0.3122],
        [0.5995],
        [0.2054],
        [0.9163],
        [0.9038],
        [0.7019],
        [0.3004],
        [0.3620],
        [0.1168],
        [0.8361],
        [0.8546],
        [0.3739],
        [0.0819],
        [0.7552],
        [0.5970],
        [0.1426],
        [0.2026],
        [0.6040],
        [0.7882],
        [0.3843],
        [0.4342],
        [0.3897],
        [0.0830]])

In [135]:
rnd.shape

torch.Size([5, 5])

In [136]:
rnd.view(5,5)

tensor([[0.3561, 0.6286, 0.3122, 0.5995, 0.2054],
        [0.9163, 0.9038, 0.7019, 0.3004, 0.3620],
        [0.1168, 0.8361, 0.8546, 0.3739, 0.0819],
        [0.7552, 0.5970, 0.1426, 0.2026, 0.6040],
        [0.7882, 0.3843, 0.4342, 0.3897, 0.0830]])

In [137]:
rnd.view(5,-1)

tensor([[0.3561, 0.6286, 0.3122, 0.5995, 0.2054],
        [0.9163, 0.9038, 0.7019, 0.3004, 0.3620],
        [0.1168, 0.8361, 0.8546, 0.3739, 0.0819],
        [0.7552, 0.5970, 0.1426, 0.2026, 0.6040],
        [0.7882, 0.3843, 0.4342, 0.3897, 0.0830]])

In [138]:
b=rnd.numpy()

In [139]:
b is rnd

False

In [140]:
b==rnd

False

In [141]:
rnd.add_(1)

tensor([[1.3561, 1.6286, 1.3122, 1.5995, 1.2054],
        [1.9163, 1.9038, 1.7019, 1.3004, 1.3620],
        [1.1168, 1.8361, 1.8546, 1.3739, 1.0819],
        [1.7552, 1.5970, 1.1426, 1.2026, 1.6040],
        [1.7882, 1.3843, 1.4342, 1.3897, 1.0830]])

In [142]:
b

array([[1.3561469, 1.628588 , 1.3121659, 1.5994713, 1.2054406],
       [1.9162608, 1.9038099, 1.7018521, 1.300431 , 1.3620112],
       [1.1168272, 1.836102 , 1.8545756, 1.3738534, 1.0819451],
       [1.7552373, 1.596976 , 1.1425626, 1.2026482, 1.6039793],
       [1.7882292, 1.3843029, 1.4341624, 1.3897266, 1.0830115]],
      dtype=float32)

In [143]:
import numpy as np

In [144]:
arr= np.array([1,2,3])

In [145]:
ar= torch.from_numpy(arr)

In [146]:
ar

tensor([1, 2, 3], dtype=torch.int32)

In [147]:
ar.add_(1)

tensor([2, 3, 4], dtype=torch.int32)

In [148]:
torch.cuda.is_available()

False

In [149]:
if torch.cuda.is_available():
    devide= torch.device("cuda")
    o= torch.ones(4,5,device= device)
    z= torch.zeros(3,4)
    z.to(device)
    o.to("cpu")

In [150]:
x= torch.randn(3,3, requires_grad=True
              )

In [151]:
x

tensor([[-0.4751, -3.0577, -1.7014],
        [ 1.1299, -0.2131,  0.9345],
        [-0.0339, -0.3116, -0.8892]], requires_grad=True)

In [152]:
y= x**2

In [153]:
y= y.mean()

In [154]:
y.backward()

In [155]:
x.grad

tensor([[-0.1056, -0.6795, -0.3781],
        [ 0.2511, -0.0474,  0.2077],
        [-0.0075, -0.0692, -0.1976]])

In [156]:
x@x

tensor([[-3.1714,  2.6343, -0.5362],
        [-0.8093, -3.7006, -2.9524],
        [-0.3057,  0.4473,  0.5572]], grad_fn=<MmBackward>)

In [157]:
x**2

tensor([[2.2569e-01, 9.3496e+00, 2.8948e+00],
        [1.2766e+00, 4.5411e-02, 8.7322e-01],
        [1.1524e-03, 9.7086e-02, 7.9065e-01]], grad_fn=<PowBackward0>)

In [158]:
x

tensor([[-0.4751, -3.0577, -1.7014],
        [ 1.1299, -0.2131,  0.9345],
        [-0.0339, -0.3116, -0.8892]], requires_grad=True)

In [159]:
y.mean(dim=0)

tensor(1.7282, grad_fn=<MeanBackward1>)

In [160]:
x.mean(dim=0)

tensor([ 0.2070, -1.1941, -0.5520], grad_fn=<MeanBackward1>)

In [161]:
x

tensor([[-0.4751, -3.0577, -1.7014],
        [ 1.1299, -0.2131,  0.9345],
        [-0.0339, -0.3116, -0.8892]], requires_grad=True)

In [162]:
x.requires_grad_(False)

tensor([[-0.4751, -3.0577, -1.7014],
        [ 1.1299, -0.2131,  0.9345],
        [-0.0339, -0.3116, -0.8892]])

In [163]:
print(x)

tensor([[-0.4751, -3.0577, -1.7014],
        [ 1.1299, -0.2131,  0.9345],
        [-0.0339, -0.3116, -0.8892]])


In [164]:
x=torch.randn(3,3, requires_grad=True)

In [165]:
x

tensor([[-0.0469,  2.3040, -0.4540],
        [-0.7695, -0.7835,  0.0898],
        [-1.1573,  1.1213, -1.5559]], requires_grad=True)

In [166]:
y=x.detach()

In [167]:
y

tensor([[-0.0469,  2.3040, -0.4540],
        [-0.7695, -0.7835,  0.0898],
        [-1.1573,  1.1213, -1.5559]])

In [168]:
y.requires_grad

False

In [169]:
y.requires_grad_(False)

tensor([[-0.0469,  2.3040, -0.4540],
        [-0.7695, -0.7835,  0.0898],
        [-1.1573,  1.1213, -1.5559]])

In [170]:
with torch.no_grad():
    y= x+2
    print(y)

tensor([[1.9531, 4.3040, 1.5460],
        [1.2305, 1.2165, 2.0898],
        [0.8427, 3.1213, 0.4441]])


In [171]:
y.requires_grad=True

In [172]:
y

tensor([[1.9531, 4.3040, 1.5460],
        [1.2305, 1.2165, 2.0898],
        [0.8427, 3.1213, 0.4441]], requires_grad=True)

In [173]:
for i in range(0,4):
    y= x+2
    y= y.mean()
    y.backward()
    print(x.grad)

tensor([[0.1111, 0.1111, 0.1111],
        [0.1111, 0.1111, 0.1111],
        [0.1111, 0.1111, 0.1111]])
tensor([[0.2222, 0.2222, 0.2222],
        [0.2222, 0.2222, 0.2222],
        [0.2222, 0.2222, 0.2222]])
tensor([[0.3333, 0.3333, 0.3333],
        [0.3333, 0.3333, 0.3333],
        [0.3333, 0.3333, 0.3333]])
tensor([[0.4444, 0.4444, 0.4444],
        [0.4444, 0.4444, 0.4444],
        [0.4444, 0.4444, 0.4444]])


In [176]:
for i in range(0,4):
    y= x+2
    y= y.mean()
    y.backward()
    print(x.grad)
    x.grad.zero_()

tensor([[0.1111, 0.1111, 0.1111],
        [0.1111, 0.1111, 0.1111],
        [0.1111, 0.1111, 0.1111]])
tensor([[0.1111, 0.1111, 0.1111],
        [0.1111, 0.1111, 0.1111],
        [0.1111, 0.1111, 0.1111]])
tensor([[0.1111, 0.1111, 0.1111],
        [0.1111, 0.1111, 0.1111],
        [0.1111, 0.1111, 0.1111]])
tensor([[0.1111, 0.1111, 0.1111],
        [0.1111, 0.1111, 0.1111],
        [0.1111, 0.1111, 0.1111]])


In [178]:
x = torch.tensor(1.0,requires_grad=True)
y = torch.tensor(2.0, requires_grad=True)

w = torch.tensor(1.0, requires_grad=True)


y_predicted = w * x
loss = (y_predicted - y)**2
print(loss)


loss.backward()
print(w.grad)

print(x.grad)
print(y.grad)


with torch.no_grad():
    w -= 0.01 * w.grad

w.grad.zero_()


tensor(1., grad_fn=<PowBackward0>)
tensor(-2.)
tensor(-2.)
tensor(2.)


tensor(0.)