In [1]:
import torch

In [18]:
w= torch.tensor([[1.0,2],[3,4],[5,6]], requires_grad=True)

In [19]:
b= torch.randn([2,3], requires_grad= True)

In [20]:
b

tensor([[-0.0395, -0.2844, -0.0307],
        [ 0.8280,  1.0607, -0.2272]], requires_grad=True)

In [21]:
b.dtype

torch.float32

In [30]:
b.shape

torch.Size([2, 3])

In [29]:
w.shape

torch.Size([3, 2])

In [24]:
w.dtype

torch.float32

In [31]:
b

tensor([[-0.0395, -0.2844, -0.0307],
        [ 0.8280,  1.0607, -0.2272]], requires_grad=True)

In [32]:
w

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]], requires_grad=True)

In [53]:
z=b.t()*w

In [54]:
b.t()

tensor([[-0.0395,  0.8280],
        [-0.2844,  1.0607],
        [-0.0307, -0.2272]], grad_fn=<TBackward0>)

In [55]:
w

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]], requires_grad=True)

In [57]:
a= torch.tensor(1.0, requires_grad= True)

In [60]:
b= torch.tensor(2.0, requires_grad= True)

In [61]:
s= a*b

In [62]:
s.backward()

In [63]:
b.grad

tensor(1.)

In [64]:
a.grad

tensor(2.)

In [65]:
?torch.full_like

Docstring:
full_like(input, fill_value, \*, dtype=None, layout=torch.strided, device=None, requires_grad=False, memory_format=torch.preserve_format) -> Tensor

Returns a tensor with the same size as :attr:`input` filled with :attr:`fill_value`.
``torch.full_like(input, fill_value)`` is equivalent to
``torch.full(input.size(), fill_value, dtype=input.dtype, layout=input.layout, device=input.device)``.

Args:
    input (Tensor): the size of :attr:`input` will determine size of the output tensor.
    fill_value: the number to fill the output tensor with.

Keyword args:
    dtype (:class:`torch.dtype`, optional): the desired data type of returned Tensor.
        Default: if ``None``, defaults to the dtype of :attr:`input`.
    layout (:class:`torch.layout`, optional): the desired layout of returned tensor.
        Default: if ``None``, defaults to the layout of :attr:`input`.
    device (:class:`torch.device`, optional): the desired device of returned tensor.
        Default: if ``None``, 

In [66]:
?torch.full

Docstring:
full(size, fill_value, *, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) -> Tensor

Creates a tensor of size :attr:`size` filled with :attr:`fill_value`. The
tensor's dtype is inferred from :attr:`fill_value`.

Args:
    size (int...): a list, tuple, or :class:`torch.Size` of integers defining the
        shape of the output tensor.
    fill_value (Scalar): the value to fill the output tensor with.

Keyword args:
    out (Tensor, optional): the output tensor.
    dtype (:class:`torch.dtype`, optional): the desired data type of returned tensor.
        Default: if ``None``, uses a global default (see :func:`torch.set_default_tensor_type`).
    layout (:class:`torch.layout`, optional): the desired layout of returned Tensor.
        Default: ``torch.strided``.
    device (:class:`torch.device`, optional): the desired device of returned tensor.
        Default: if ``None``, uses the current device for the default tensor type
        (see :func:`tor

In [68]:
torch.full([2,3],56)

tensor([[56, 56, 56],
        [56, 56, 56]])

In [72]:
torch.full_like(w,65)

tensor([[65., 65.],
        [65., 65.],
        [65., 65.]])

In [73]:
w.shape

torch.Size([3, 2])

In [74]:
w.to_numpy()

AttributeError: 'Tensor' object has no attribute 'to_numpy'

In [75]:
import numpy as np

In [76]:
arr= np.asarray([1,2,3])

In [80]:
torch.from_numpy(arr)

tensor([1, 2, 3], dtype=torch.int32)

In [88]:
# b.numpy()

In [86]:
c= torch.tensor([1.0,4,5,3,2])

In [87]:
c.numpy()

array([1., 4., 5., 3., 2.], dtype=float32)