In [1]:
import torch

In [6]:
z=torch.zeros(2,dtype=torch.int32)

In [7]:
z

tensor([0, 0], dtype=torch.int32)

In [8]:
o=torch.ones(2,3,dtype= torch.float16)

In [9]:
o

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float16)

In [10]:
r=torch.randn(2,2)

In [11]:
r

tensor([[-0.0326,  0.1741],
        [-1.2384,  1.4507]])

In [16]:
r.shape

torch.Size([2, 2])

In [17]:
r.size()

torch.Size([2, 2])

In [20]:
r=r.reshape([4,1])

In [21]:
r

tensor([[-0.0326],
        [ 0.1741],
        [-1.2384],
        [ 1.4507]])

In [22]:
torch.add(r,r)

tensor([[-0.0652],
        [ 0.3481],
        [-2.4768],
        [ 2.9014]])

In [23]:
r.add(r)

tensor([[-0.0652],
        [ 0.3481],
        [-2.4768],
        [ 2.9014]])

In [24]:
r

tensor([[-0.0326],
        [ 0.1741],
        [-1.2384],
        [ 1.4507]])

In [25]:
r.add_(r)

tensor([[-0.0652],
        [ 0.3481],
        [-2.4768],
        [ 2.9014]])

In [26]:
r

tensor([[-0.0652],
        [ 0.3481],
        [-2.4768],
        [ 2.9014]])