In [1]:
import torch

In [6]:
z=torch.zeros(2,dtype=torch.int32)

In [7]:
z

tensor([0, 0], dtype=torch.int32)

In [8]:
o=torch.ones(2,3,dtype= torch.float16)

In [9]:
o

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float16)

In [10]:
r=torch.randn(2,2)

In [11]:
r

tensor([[-0.0326,  0.1741],
        [-1.2384,  1.4507]])

In [16]:
r.shape

torch.Size([2, 2])

In [17]:
r.size()

torch.Size([2, 2])

In [20]:
r=r.reshape([4,1])

In [21]:
r

tensor([[-0.0326],
        [ 0.1741],
        [-1.2384],
        [ 1.4507]])

In [22]:
torch.add(r,r)

tensor([[-0.0652],
        [ 0.3481],
        [-2.4768],
        [ 2.9014]])

In [23]:
r.add(r)

tensor([[-0.0652],
        [ 0.3481],
        [-2.4768],
        [ 2.9014]])

In [24]:
r

tensor([[-0.0326],
        [ 0.1741],
        [-1.2384],
        [ 1.4507]])

In [25]:
r.add_(r)

tensor([[-0.0652],
        [ 0.3481],
        [-2.4768],
        [ 2.9014]])

In [26]:
r

tensor([[-0.0652],
        [ 0.3481],
        [-2.4768],
        [ 2.9014]])

In [27]:
r.div(r)

tensor([[1.],
        [1.],
        [1.],
        [1.]])

In [28]:
torch.div(r,r)

tensor([[1.],
        [1.],
        [1.],
        [1.]])

In [29]:
rnd=torch.rand(5,5)

In [30]:
rnd[1,1]

tensor(0.1276)

In [31]:
rnd[1,:2]

tensor([0.0884, 0.1276])

In [32]:
rnd[1,:4]

tensor([0.0884, 0.1276, 0.4430, 0.3866])

In [33]:
rnd[:2,:2]

tensor([[0.8592, 0.0591],
        [0.0884, 0.1276]])

In [36]:
type(rnd[1,1].item())

float

In [37]:
rnd.shape

torch.Size([5, 5])

In [38]:
rnd.reshape([25,1])

tensor([[0.8592],
        [0.0591],
        [0.4778],
        [0.6956],
        [0.4289],
        [0.0884],
        [0.1276],
        [0.4430],
        [0.3866],
        [0.2534],
        [0.9830],
        [0.2122],
        [0.2083],
        [0.3700],
        [0.8170],
        [0.4541],
        [0.2175],
        [0.5613],
        [0.9206],
        [0.7744],
        [0.6442],
        [0.1253],
        [0.9238],
        [0.5321],
        [0.2966]])

In [39]:
rnd.shape

torch.Size([5, 5])

In [40]:
rnd.view(5,5)

tensor([[0.8592, 0.0591, 0.4778, 0.6956, 0.4289],
        [0.0884, 0.1276, 0.4430, 0.3866, 0.2534],
        [0.9830, 0.2122, 0.2083, 0.3700, 0.8170],
        [0.4541, 0.2175, 0.5613, 0.9206, 0.7744],
        [0.6442, 0.1253, 0.9238, 0.5321, 0.2966]])

In [41]:
rnd.view(5,-1)

tensor([[0.8592, 0.0591, 0.4778, 0.6956, 0.4289],
        [0.0884, 0.1276, 0.4430, 0.3866, 0.2534],
        [0.9830, 0.2122, 0.2083, 0.3700, 0.8170],
        [0.4541, 0.2175, 0.5613, 0.9206, 0.7744],
        [0.6442, 0.1253, 0.9238, 0.5321, 0.2966]])

In [42]:
b=rnd.numpy()

In [45]:
b is rnd

False

In [46]:
b==rnd

False

In [47]:
rnd.add_(1)

tensor([[1.8592, 1.0591, 1.4778, 1.6956, 1.4289],
        [1.0884, 1.1276, 1.4430, 1.3866, 1.2534],
        [1.9830, 1.2122, 1.2083, 1.3700, 1.8170],
        [1.4541, 1.2175, 1.5613, 1.9206, 1.7744],
        [1.6442, 1.1253, 1.9238, 1.5321, 1.2966]])

In [48]:
b

array([[1.8592397, 1.0591218, 1.477802 , 1.6956408, 1.4288995],
       [1.0883725, 1.1275898, 1.4430497, 1.3865991, 1.2534418],
       [1.9830025, 1.2121788, 1.2083477, 1.3699511, 1.817006 ],
       [1.4541416, 1.2175491, 1.561315 , 1.9206417, 1.7743969],
       [1.6441545, 1.12534  , 1.9238284, 1.5321087, 1.2965789]],
      dtype=float32)

In [49]:
import numpy as np

In [50]:
arr= np.array([1,2,3])

In [52]:
ar= torch.from_numpy(arr)

In [53]:
ar

tensor([1, 2, 3], dtype=torch.int32)

In [54]:
ar.add_(1)

tensor([2, 3, 4], dtype=torch.int32)

In [62]:
torch.cuda.is_available()

False

In [63]:
if torch.cuda.is_available():
    devide= torch.device("cuda")
    o= torch.ones(4,5,device= device)
    z= torch.zeros(3,4)
    z.to(device)
    o.to("cpu")