In [1]:
import torch

In [18]:
w= torch.tensor([[1.0,2],[3,4],[5,6]], requires_grad=True)

In [19]:
b= torch.randn([2,3], requires_grad= True)

In [20]:
b

tensor([[-0.0395, -0.2844, -0.0307],
        [ 0.8280,  1.0607, -0.2272]], requires_grad=True)

In [21]:
b.dtype

torch.float32

In [30]:
b.shape

torch.Size([2, 3])

In [29]:
w.shape

torch.Size([3, 2])

In [24]:
w.dtype

torch.float32

In [31]:
b

tensor([[-0.0395, -0.2844, -0.0307],
        [ 0.8280,  1.0607, -0.2272]], requires_grad=True)

In [32]:
w

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]], requires_grad=True)

In [53]:
z=b.t()*w

In [54]:
b.t()

tensor([[-0.0395,  0.8280],
        [-0.2844,  1.0607],
        [-0.0307, -0.2272]], grad_fn=<TBackward0>)

In [55]:
w

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]], requires_grad=True)

In [57]:
a= torch.tensor(1.0, requires_grad= True)

In [60]:
b= torch.tensor(2.0, requires_grad= True)

In [61]:
s= a*b

In [62]:
s.backward()

In [63]:
b.grad

tensor(1.)

In [64]:
a.grad

tensor(2.)

In [65]:
?torch.full_like

Docstring:
full_like(input, fill_value, \*, dtype=None, layout=torch.strided, device=None, requires_grad=False, memory_format=torch.preserve_format) -> Tensor

Returns a tensor with the same size as :attr:`input` filled with :attr:`fill_value`.
``torch.full_like(input, fill_value)`` is equivalent to
``torch.full(input.size(), fill_value, dtype=input.dtype, layout=input.layout, device=input.device)``.

Args:
    input (Tensor): the size of :attr:`input` will determine size of the output tensor.
    fill_value: the number to fill the output tensor with.

Keyword args:
    dtype (:class:`torch.dtype`, optional): the desired data type of returned Tensor.
        Default: if ``None``, defaults to the dtype of :attr:`input`.
    layout (:class:`torch.layout`, optional): the desired layout of returned tensor.
        Default: if ``None``, defaults to the layout of :attr:`input`.
    device (:class:`torch.device`, optional): the desired device of returned tensor.
        Default: if ``None``, 

In [66]:
?torch.full

Docstring:
full(size, fill_value, *, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) -> Tensor

Creates a tensor of size :attr:`size` filled with :attr:`fill_value`. The
tensor's dtype is inferred from :attr:`fill_value`.

Args:
    size (int...): a list, tuple, or :class:`torch.Size` of integers defining the
        shape of the output tensor.
    fill_value (Scalar): the value to fill the output tensor with.

Keyword args:
    out (Tensor, optional): the output tensor.
    dtype (:class:`torch.dtype`, optional): the desired data type of returned tensor.
        Default: if ``None``, uses a global default (see :func:`torch.set_default_tensor_type`).
    layout (:class:`torch.layout`, optional): the desired layout of returned Tensor.
        Default: ``torch.strided``.
    device (:class:`torch.device`, optional): the desired device of returned tensor.
        Default: if ``None``, uses the current device for the default tensor type
        (see :func:`tor

In [68]:
torch.full([2,3],56)

tensor([[56, 56, 56],
        [56, 56, 56]])

In [72]:
torch.full_like(w,65)

tensor([[65., 65.],
        [65., 65.],
        [65., 65.]])

In [73]:
w.shape

torch.Size([3, 2])

In [75]:
import numpy as np

In [76]:
arr= np.asarray([1,2,3])

In [80]:
torch.from_numpy(arr)

tensor([1, 2, 3], dtype=torch.int32)

In [88]:
# b.numpy()

In [86]:
c= torch.tensor([1.0,4,5,3,2])

In [87]:
c.numpy()

array([1., 4., 5., 3., 2.], dtype=float32)

In [89]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')
inputs= torch.from_numpy(inputs)

In [90]:
inputs

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])

In [91]:
inputs.shape

torch.Size([5, 3])

In [92]:
arr

array([1, 2, 3])

In [93]:
arr2= np.array([[[1],[2],[3]]])

In [94]:
arr*arr2

array([[[1, 2, 3],
        [2, 4, 6],
        [3, 6, 9]]])

In [95]:
arr2*arr

array([[[1, 2, 3],
        [2, 4, 6],
        [3, 6, 9]]])

In [96]:
arr2.shape

(1, 3, 1)

In [97]:
arr.shape

(3,)

In [105]:
arr3= np.array([[1],[2],[3]]).reshape([1,3])

In [106]:
arr3.shape

(1, 3)

In [112]:
arr=arr.reshape([3,1])

In [109]:
arr*arr3

array([[1, 4, 9]])

In [110]:
arr3*arr

array([[1, 4, 9]])

In [117]:
arr3.shape

(1, 3)

In [114]:
arr.shape

(3, 1)

In [115]:
arr*arr3

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [116]:
arr3*arr

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [119]:
inputs

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])

In [125]:
# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype='float32')
targets= torch.from_numpy(targets)

In [126]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

In [161]:
w= torch.randn((2,3), requires_grad =True)

In [162]:
w

tensor([[-1.9292,  0.2798,  0.3654],
        [-0.2899,  0.3852, -0.3161]], requires_grad=True)

In [163]:
b= torch.randn((2,1), requires_grad=True)

In [164]:
inputs.shape

torch.Size([5, 3])

In [165]:
inputs

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])

In [166]:
w.shape

torch.Size([2, 3])

In [167]:
inputs.shape

torch.Size([5, 3])

In [171]:
inputs

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])

In [172]:
w

tensor([[-1.9292,  0.2798,  0.3654],
        [-0.2899,  0.3852, -0.3161]], requires_grad=True)

In [173]:
w@inputs.t()

tensor([[-106.3711, -127.5470, -109.1541, -171.2235,  -80.6749],
        [  -8.9431,  -12.7091,    8.0682,  -24.6993,   -5.1461]],
       grad_fn=<MmBackward0>)

In [174]:
inputs@w.t()

tensor([[-106.3711,   -8.9431],
        [-127.5470,  -12.7091],
        [-109.1541,    8.0682],
        [-171.2235,  -24.6993],
        [ -80.6749,   -5.1461]], grad_fn=<MmBackward0>)

In [176]:
inputs.shape

torch.Size([5, 3])

In [177]:
w.shape

torch.Size([2, 3])

In [178]:
def model(x):
    return x @ w.t() + b

In [ ]:
# pred= model(inputs)

In [180]:
# Weights and biases
w = torch.randn(2, 3, requires_grad=True)
b = torch.randn(2, requires_grad=True)
print(w)
print(b)

tensor([[ 0.6751, -1.3273,  0.3191],
        [-0.2409,  0.0214, -0.9760]], requires_grad=True)
tensor([1.1565, 0.0413], requires_grad=True)


In [181]:
pred= model(inputs)

In [183]:
(pred-targets)

tensor([[ -80.7710, -128.0781],
        [-114.7919, -183.4607],
        [-218.4625, -207.6550],
        [   2.7465,  -96.7234],
        [-160.3473, -201.8449]], grad_fn=<SubBackward0>)

In [191]:
# MSE loss
def mse(t1, t2):
    global diff
    diff = t1 - t2
    print(diff*diff)
    return torch.sum(diff * diff) / diff.numel()

In [192]:
loss=mse(pred,targets)

tensor([[6.5240e+03, 1.6404e+04],
        [1.3177e+04, 3.3658e+04],
        [4.7726e+04, 4.3121e+04],
        [7.5434e+00, 9.3554e+03],
        [2.5711e+04, 4.0741e+04]], grad_fn=<MulBackward0>)


In [193]:
loss

tensor(23642.4961, grad_fn=<DivBackward0>)

In [194]:
diff.shape

torch.Size([5, 2])

In [195]:
diff

tensor([[ -80.7710, -128.0781],
        [-114.7919, -183.4607],
        [-218.4625, -207.6550],
        [   2.7465,  -96.7234],
        [-160.3473, -201.8449]], grad_fn=<SubBackward0>)

In [196]:
pred

tensor([[-24.7710, -58.0781],
        [-33.7919, -82.4607],
        [-99.4625, -74.6550],
        [ 24.7465, -59.7234],
        [-57.3473, -82.8449]], grad_fn=<AddBackward0>)

In [198]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

In [199]:
# Compute gradients
loss.backward()

In [200]:
# Gradients for weights
print(w)
print(w.grad)

tensor([[ 0.6751, -1.3273,  0.3191],
        [-0.2409,  0.0214, -0.9760]], requires_grad=True)
tensor([[ -9226.4805, -12012.5117,  -6922.6699],
        [-13580.7383, -15217.5508,  -9400.1475]])


In [201]:
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5

In [202]:
w

tensor([[ 0.7673, -1.2072,  0.3883],
        [-0.1051,  0.1736, -0.8820]], requires_grad=True)

In [203]:
b

tensor([1.1576, 0.0430], requires_grad=True)

In [204]:
preds= model(inputs)

In [205]:
loss= mse(preds,targets)

tensor([[ 3970.1892, 10800.3496],
        [ 8352.7119, 23010.7773],
        [36222.6016, 28898.1211],
        [  395.4308,  5306.7964],
        [18934.2988, 29338.0664]], grad_fn=<MulBackward0>)


In [206]:
loss

tensor(16522.9336, grad_fn=<DivBackward0>)

In [210]:
w.grad.zero_()

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [211]:
b.grad.zero_()

tensor([0., 0.])

In [212]:
# Compute gradients
loss.backward()
print(w.grad)
print(b.grad)

# Adjust weights & reset gradients
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

tensor([[ -7388.1465, -10024.4277,  -5698.7285],
        [-11085.8271, -12533.3770,  -7744.4033]])
tensor([ -92.4883, -133.9487])


In [213]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor([[ 2347.2429,  7073.3613],
        [ 5212.8901, 15779.8350],
        [27941.0488, 19338.2383],
        [ 1145.2344,  2839.1956],
        [14134.9902, 21368.5645]], grad_fn=<MulBackward0>)
tensor(11718.0605, grad_fn=<DivBackward0>)


In [214]:
loss

tensor(11718.0605, grad_fn=<DivBackward0>)