In [97]:
import torch.nn as nn
import torch

In [98]:
import numpy as np

In [99]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70], 
                   [74, 66, 43], 
                   [91, 87, 65], 
                   [88, 134, 59], 
                   [101, 44, 37], 
                   [68, 96, 71], 
                   [73, 66, 44], 
                   [92, 87, 64], 
                   [87, 135, 57], 
                   [103, 43, 36], 
                   [68, 97, 70]], 
                  dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119],
                    [57, 69], 
                    [80, 102], 
                    [118, 132], 
                    [21, 38], 
                    [104, 118], 
                    [57, 69], 
                    [82, 100], 
                    [118, 134], 
                    [20, 38], 
                    [102, 120]], 
                   dtype='float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [100]:
inputs

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 74.,  66.,  43.],
        [ 91.,  87.,  65.],
        [ 88., 134.,  59.],
        [101.,  44.,  37.],
        [ 68.,  96.,  71.],
        [ 73.,  66.,  44.],
        [ 92.,  87.,  64.],
        [ 87., 135.,  57.],
        [103.,  43.,  36.],
        [ 68.,  97.,  70.]])

In [101]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])

In [102]:
from torch.utils.data import TensorDataset

In [103]:
# Define dataset
train_ds = TensorDataset(inputs, targets)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]), tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [104]:
from torch.utils.data import DataLoader

In [105]:
# Define data loader
batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle=True)

In [106]:
for xa, xb in train_dl:
    print(xa, "\n" ,xb, "\n")

tensor([[101.,  44.,  37.],
        [ 88., 134.,  59.],
        [ 73.,  66.,  44.],
        [ 74.,  66.,  43.],
        [102.,  43.,  37.]]) 
 tensor([[ 21.,  38.],
        [118., 132.],
        [ 57.,  69.],
        [ 57.,  69.],
        [ 22.,  37.]]) 

tensor([[ 68.,  96.,  71.],
        [ 91.,  88.,  64.],
        [103.,  43.,  36.],
        [ 87., 134.,  58.],
        [ 87., 135.,  57.]]) 
 tensor([[104., 118.],
        [ 81., 101.],
        [ 20.,  38.],
        [119., 133.],
        [118., 134.]]) 

tensor([[69., 96., 70.],
        [73., 67., 43.],
        [91., 87., 65.],
        [92., 87., 64.],
        [68., 97., 70.]]) 
 tensor([[103., 119.],
        [ 56.,  70.],
        [ 80., 102.],
        [ 82., 100.],
        [102., 120.]]) 



In [107]:
# Define model
model = nn.Linear(3, 2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[ 0.4447, -0.5614,  0.0239],
        [ 0.5705,  0.5617,  0.0301]], requires_grad=True)
Parameter containing:
tensor([0.4223, 0.1114], requires_grad=True)


In [108]:
# Parameters
list(model.parameters())

[Parameter containing:
 tensor([[ 0.4447, -0.5614,  0.0239],
         [ 0.5705,  0.5617,  0.0301]], requires_grad=True),
 Parameter containing:
 tensor([0.4223, 0.1114], requires_grad=True)]

In [109]:
# Generate predictions
preds = model(inputs)
preds

tensor([[ -3.7033,  80.6838],
        [ -6.9866, 103.3802],
        [-34.7343, 126.7551],
        [ 22.5226,  83.5662],
        [-21.1171,  95.5040],
        [ -2.6972,  80.6926],
        [ -6.4012, 102.8486],
        [-34.2657, 127.3557],
        [ 21.5165,  83.5575],
        [-21.5378,  94.9637],
        [ -3.1179,  80.1522],
        [ -5.9805, 103.3889],
        [-35.3196, 127.2866],
        [ 22.9433,  84.1066],
        [-22.1231,  95.4953]], grad_fn=<AddmmBackward0>)

In [110]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])

In [111]:
import torch.nn.functional as f

In [112]:
loss= f.mse_loss(preds,targets)

In [113]:
loss

tensor(5304.9321, grad_fn=<MseLossBackward0>)

In [114]:
loss_fn= f.mse_loss

In [115]:
# Utility function to train the model
def fit(num_epochs, model, loss_fn, opt, train_dl):
    
    global losses
    losses=[]
    # Repeat for given number of epochs
    for epoch in range(num_epochs):
        
        # Train with batches of data
        for xb,yb in train_dl:
            
            # 1. Generate predictions
            pred = model(xb)
            
            
            # 2. Calculate loss
            loss = loss_fn(pred, yb)
            losses.append(loss)
            
            # 3. Compute gradients
            loss.backward()
            
            
            # 4. Update parameters using gradients
            opt.step()
            
            # 5. Reset the gradients to zero
            opt.zero_grad()
        
        # Print the progress
        if (epoch+1) % 10 == 0:
            print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))
        
        
            
        

In [116]:
opt= torch.optim.SGD(model.parameters(), lr= 1e-5)

In [127]:
pred=fit(150,model,loss_fn,opt,train_dl)

Epoch [10/150], Loss: 51.6523
Epoch [20/150], Loss: 35.5668
Epoch [30/150], Loss: 21.3076
Epoch [40/150], Loss: 21.9264
Epoch [50/150], Loss: 20.6011
Epoch [60/150], Loss: 18.9631
Epoch [70/150], Loss: 18.5258
Epoch [80/150], Loss: 16.9983
Epoch [90/150], Loss: 14.8630
Epoch [100/150], Loss: 7.1345
Epoch [110/150], Loss: 16.9184
Epoch [120/150], Loss: 13.9996
Epoch [130/150], Loss: 19.3502
Epoch [140/150], Loss: 9.7409
Epoch [150/150], Loss: 8.3321


In [128]:
losses[-1]

tensor(8.3321, grad_fn=<MseLossBackward0>)

In [129]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])

In [130]:
pre= model(inputs)

In [131]:
pre

tensor([[ 57.2193,  70.7694],
        [ 81.1476,  97.7158],
        [119.7560, 138.5240],
        [ 21.8790,  39.5855],
        [ 99.7860, 112.5495],
        [ 55.9674,  69.6385],
        [ 80.8399,  97.2909],
        [119.9606, 138.8424],
        [ 23.1309,  40.7164],
        [100.7302, 113.2555],
        [ 56.9115,  70.3445],
        [ 79.8957,  96.5849],
        [120.0638, 138.9489],
        [ 20.9348,  38.8795],
        [101.0379, 113.6804]], grad_fn=<AddmmBackward0>)